#!/bin/bash
# CUDA SM_120 Lockout Removal - Installation Script
# Generated by JARVIS Cognitive Architecture

set -e  # Exit on error

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║  🔧 CUDA SM_120 Lockout Removal                          ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "❌ Please run as root (sudo)"
    exit 1
fi

# Backup original
ORIGINAL="/usr/lib/x86_64-linux-gnu/libcuda.so.1.1"
BACKUP="/usr/lib/x86_64-linux-gnu/libcuda.so.1.1.backup"
PATCHED="/mnt/user-data/outputs/libcuda.so.1.1.patched"

echo "📦 Creating backup..."
if [ ! -f "$BACKUP" ]; then
    cp "$ORIGINAL" "$BACKUP"
    echo "✅ Backup created: $BACKUP"
else
    echo "ℹ️  Backup already exists"
fi

echo ""
echo "🔧 Installing patched driver..."
cp "$PATCHED" "$ORIGINAL"
chmod 755 "$ORIGINAL"

echo ""
echo "🔄 Updating library cache..."
ldconfig

echo ""
echo "✅ Installation complete!"
echo ""
echo "📊 Patches applied:"
echo "   1. NOP comparison at 0x186b50"

echo ""
echo "🚀 Next steps:"
echo "   1. Restart your application"
echo "   2. Test SM_120 functionality"
echo "   3. If issues occur, restore backup:"
echo "      sudo cp $BACKUP $ORIGINAL"
echo "      sudo ldconfig"
echo ""
